name: wedzy_duo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  shared_preferences: ^2.0.15
  get: ^4.6.5
  fluttertoast: ^8.2.2
  lottie: ^2.3.2
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.4
  get_storage: ^2.1.1
  flutter_svg: ^2.0.5
  flutter_switch: ^0.3.2
  pin_code_fields: ^8.0.1
  buttons_tabbar: ^1.3.7
  percent_indicator: ^4.2.3
  syncfusion_flutter_calendar: ^20.3.47
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^20.4.54
  flutter_rating_bar: ^4.0.1
  flutter_share: ^2.0.0
  curved_navigation_bar: ^1.0.3
  dropdown_button2: ^2.1.4
  fdottedline_nullsafety: ^2.0.1
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  dotted_border: ^2.0.0+3
  fl_chart: ^0.63.0
  accordion: ^2.5.1
  timer_button: ^2.0.0
  another_flushbar: ^1.12.30
  flutter_speed_dial: ^7.0.0

  local_auth: ^2.1.6
  flutter_dash: ^1.0.0

  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/json/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  